name: Deploy Frontend to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Dependencies
      run: |
        npm install
        npm install -g @angular/cli
        npm install angular-cli-ghpages
      working-directory: ./website

    - name: Build Project
      run: ng build --configuration production --base-href "/"
      working-directory: ./website

    - name: Set Git identity
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Debug build output
      run: |
        echo "Checking build output location..."
        ls -la dist/
        ls -la dist/improv-index/
      working-directory: ./website

    - name: Authenticate with GitHub
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

    - name: Deploy to GitHub Pages
      run: |
        ng deploy --base-href=/ --dir=dist/improv-index/browser --cname=www.improvindex.org
      working-directory: ./website
